### ISSUE TITLE
Broken links on main Serialization and Deserialization pages

### ISSUE THREAD

**Issue by aniketschneider** [jsonapi-rb/jsonapi-rb.github.io#18]
On these pages:

http://jsonapi-rb.org/guides/serialization/
http://jsonapi-rb.org/guides/deserialization/

The links in the body content are broken - for example, http://jsonapi-rb.org/guides/serialization/guides/serialization/defining.html
The links in the sidebar to the same pages are correct - the corresponding correct link from the sidebar is: http://jsonapi-rb.org/guides/serialization/defining.html

**Comment by beauby** [comment]
Thanks for reporting this @aniketschneider – would you mind issuing a PR to fix it? Otherwise I'll do it later tonight.

**Comment by aniketschneider** [comment]
I wanted to do just that, but I am actually not able to reproduce this problem when running the site locally with `middleman server` - the links look fine there.
